---
abstract: 'Add debugger command to see stack trace as HTML'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires:
  Carp: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200008, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DB-Pluggable-StackTraceAsHTML
provides:
  DB::Pluggable::Plugin::StackTraceAsHTML:
    file: lib/DB/Pluggable/Plugin/StackTraceAsHTML.pm
    version: 1.111750
requires:
  Browser::Open: 0
  DB::Pluggable::Role::Initializer: 0
  Devel::StackTrace::AsHTML: 0
  Devel::StackTrace::WithLexicals: 0
  File::Slurp: 0
  Role::Basic: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=DB-Pluggable-StackTraceAsHTML
  homepage: http://search.cpan.org/dist/DB-Pluggable-StackTraceAsHTML/
  repository: git://github.com/hanekomu/DB-Pluggable-StackTraceAsHTML.git
version: 1.111750
